### ISSUE TITLE
Ceph rbd resize on Windows server 2019

### ISSUE THREAD

**Issue by kuoshin** [cloudbase/wnbd#119]
Hi All

I adjusts the rbd space from the server side, but the rbd space mounted by windows does not change accordingly. 
Is there any way to adjust it?

![rbd](https://user-images.githubusercontent.com/2892047/228825622-11d1626b-20f3-4a17-b87b-39ca5d607e4c.png)

**Comment by petrutlucian94** [comment]
Hi,

Which rbd version are you using on Windows? This feature was merged a couple of months ago [1] and backported downstream to Quincy [2].

The latest Ceph Quincy MSI available here [3] includes the live resize feature.

[1] https://github.com/ceph/ceph/pull/48848
[2] https://github.com/cloudbase/ceph/tree/quincy-downstream
[3] https://cloudba.se/ceph-win-latest-quincy

**Comment by kuoshin** [comment]
Sorry I find the solution

create a new volume and mount it a drive letter:Computer Management > Disk Management > Select unallocated disk space you need > Right-click mouse button > New Simple Volume > Select needed size > Assign drive letter > Format partition
    To shrink or expand volumes:Computer Management > Disk Management > Select the partition you wish to shrink/expand > Right-click on the mouse button to shrink or expand.
