### ISSUE TITLE
[Feature Request] Support continual remount/remap attempts

### ISSUE THREAD

**Issue by nf-brentsaner** [cloudbase/wnbd#130]
Most of our storage infrastructure (Ceph) is Linux. However, while `wnbd` has been invaluable for the odd Windows machines that need to stick around, during maintenance reboots for the cluster nodes, RBD devices on Windows clients become unmapped.

Which is, you know, expected.

Except due to the density of some of the e.g. OSD hosts, reboots can take a **good amount** of time - in the order of ~10 minutes. This causes RBD mappings to disappear on Windows hosts, and it seems that they do not reconnect on their own.

Would modifying the `StaleConnTimeoutMs`/`StaleReqTimeoutMs`/`RemoveStaleConnections` be the proper path towards rectifying this or do they only refer to releasing already "dead" resources?

If the latter, would it be possible to add a boolean `ContinualReconnect` (try to reconnect/remap) and `ReconnectIntervalMs` (try to reconnect every *n* ms) to the driver options that would cause wnbd to try to reconnect/remap continuously?

**Comment by petrutlucian94** [comment]
Interesting issue, thanks for bringing it up. The main reason why we're cleaning up stale connection is that after a few minutes, the host can become unresponsive, especially when Windows tries to read the partition table or flush its cache.

According to your situation, you might try bumping ``StaleConnTimeoutMs`` to 900000 (15 minutes) or even disable the automatic cleanup (``RemoveStaleConnections``). Those are WNBD driver settings, Ceph should be able to reconnect once the OSDs come back up. Here's a list of Ceph connection settings that you should check:

* ``client_mount_timeout`` (the description is misleading. It applies to any monitor connection, not just CephFS mounts)
* ``rados_mon_op_timeout`` (infinite by default)
* ``rados_osd_op_timeout`` (you might try setting 20s or 30s, by failing early you avoid having the disks marked as stale)

A small implementation detail: the WNBD driver is Ceph agnostic, it's simply forwarding IO requests to the userspace rbd-wnbd daemon. For this reason, once a disk is disconnected, the driver can't bring it back.

**Comment by petrutlucian94** [comment]
I'm a bit surprised that you're experiencing downtime though, you may want to temporarily disable rebalancing when rebooting OSDs: https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/8/html/director_installation_and_usage/sect-rebooting-ceph

**Comment by petrutlucian94** [comment]
I'll close the issue considering that the WNBD driver cannot reestablish closed connections and the situation can be avoided by adjusting the timeouts and automatic cleanup settings as mentioned above.

Please let me know if you have any further questions.
