### ISSUE TITLE
CallNamedPipe ret errcode 22

### ISSUE THREAD

**Issue by luckyho** [cloudbase/wnbd#138]
Mount rbd on win10, rbd wnbd returns -22
The screenshot is below
![image](https://github.com/user-attachments/assets/156747cd-7f79-4185-9476-4a265fcde756)

ceph version : 15.2.17
rbd wnbd version : 16.4.10
![image](https://github.com/user-attachments/assets/8344ea99-8421-46f9-a285-bc0ff45906fc)

**Comment by petrutlucian94** [comment]
Hi, I suggest using the following for debugging purposes:
``rbd-wnbd map rendersphere/test1-img01 -n client.rendersphere -f``

``-f`` tells it to run as a daemon and map the device in the same process instead of using the centralized service, thus it's easier to obtain the actual error.

**Comment by luckyho** [comment]
ok, i will try it

**Comment by ArthurHe666** [comment]
I tried, adding -f will not cause map failure, without adding -f, when the system just starts, there will be a higher probability of failure

Here are some logs

**Comment by ArthurHe666** [comment]
when adding -f to run , it works well. but If -f is not added, especially after the system is restarted, the probability of map failure will be very high

There are some logs below
![image](https://github.com/user-attachments/assets/c22edba5-a2ff-4a7d-81cf-9da6d80563f2)

![image](https://github.com/user-attachments/assets/910d24fb-2786-4347-bc2d-5fe530ea386e)

![image](https://github.com/user-attachments/assets/6edb2c5f-ab12-4cf5-8b1b-a902d409f1fa)

**Comment by ArthurHe666** [comment]
![image](https://github.com/user-attachments/assets/f0b63226-1df6-490c-a109-1f1e7cd33da0)
it looks like timeout？

![image](https://github.com/user-attachments/assets/92d7bd65-5601-4d0e-9d2a-e75b04d2de2c)
the rbd server is start at 12:37

**Comment by petrutlucian94** [comment]
Interesting, it does look like a timeout. This old version of Ceph (Pacific) spawns a separate process for each mapped image and for some reason it fails in this case.

Newer versions use a single daemon process per host and include many other bug fixes that have not been ported to Pacific, which is no longer maintained. Would it be possible to upgrade to Ceph Squid or Reef?

**Comment by ArthurHe666** [comment]
when adding -f to run，Some clients also took more than 100 seconds to complete the RBD map request.
In the process, we found some problems
When a request is sent to ceph to obtain snapshot information of rbd image, There are a lot of socket reconnections Appears when the contents of a socket are read, This process lasted for 100 seconds

Here are some logs

Send a request to get a snapshot
![image](https://github.com/user-attachments/assets/a55d7101-34ce-4fd6-bc90-cb68d02ffa6e)

Failed to read socket contents and reconnect
![image](https://github.com/user-attachments/assets/0a06b130-c070-4285-b3f0-e72d149ba1eb)

Failed to read socket contents and reconnect again
![image](https://github.com/user-attachments/assets/d5e32688-7911-43f2-b705-63daad74e37c)

OK，It finally returned
![image](https://github.com/user-attachments/assets/7028e936-7ef5-4c8d-9ab9-bc1fcb4d034f)


additional, this rbd block has more than 200 snapshots,  Does this have an impact, but I didn't get any socket error there in ceph storage



Hope to hear from you

**Comment by petrutlucian94** [comment]
Having such a large number of rbd snapshots may degrade the cluster performance: https://www.spinics.net/lists/ceph-users/msg38519.html

Have you seen similar timeouts with Linux RBD clients? Again, I strongly recommend upgrading to a newer Ceph release. We had many bug fixes that addressed connectivity issues (OSD sessions shared across mappings in order to reduce the number of TCP sessions, switched to mingw-llvm to avoid some locking issues w/ mingw-gcc, changed polling mechanism and many more).

**Comment by ArthurHe666** [comment]
Thanks for the suggestion, I've already suggested upgrading the RBD client
I test it in Linux，It works fine, I will continue to test and observe
additional, is there any similar issues resolved in a higher version?

**Comment by petrutlucian94** [comment]
Indeed, there were a few potentially related bug fixes in recent Ceph releases.
