### ISSUE TITLE
Ceph Pacific for Windows x64 on Windows Server 2019

### ISSUE THREAD

**Issue by jblake1991** [cloudbase/wnbd#83]
Hello.

After installing the Ceph Pacific and Quincy for Windows x64 on Windows Server 2019 using the MSI, which is on a VMware system, the server no longer boots correctly after a reboot. Has anyone else seen this issue?

**Comment by kuoshin** [comment]
I have encountered the same problem, is there any way to solve it?

**Comment by kuoshin** [comment]
> I have encountered the same problem, is there any way to solve it?

I have found a solution, as long as the **secure boot** is turned off, it can be turned on normally

**Comment by petrutlucian94** [comment]
We're in the process of certifying the driver and expect to have it signed by MS soon. In the meantime, secure boot has to be disabled.
